#!/bin/bash

set -e

usage() {
	echo "usage: ./bets_lotofacil TUPLE_SIZE GROUP_LABEL" 1>&2
	exit 1
}

TUPLE_SIZE=$1
test -n "$TUPLE_SIZE" || usage
shift
GROUP_LABEL=$1
test -n "$GROUP_LABEL" || usage
shift
test -z "$1" || usage

RESULT_DIR="lotofacil/${GROUP_LABEL}"
mkdir -p $RESULT_DIR

ALL_BETS_FILE_NAME="${TUPLE_SIZE}-15-25.all"
ALL_BETS_FILE="${RESULT_DIR}/${ALL_BETS_FILE_NAME}"
./bets "$TUPLE_SIZE" 15 25 1>$ALL_BETS_FILE
(
	cd $RESULT_DIR
	split -d -l 2 -a 4 $ALL_BETS_FILE_NAME 'bets.'
)

##FIXME: debug
#echo -n 1>$RESULT_DIR/bets.0000
#for I in 0 1 ; do
	#seq -s ' ' 1 25 1>>$RESULT_DIR/bets.0000
#done

bets_to_data() {
	local SECTOR='-1'
	local LINE
	local COLUMN
	while read BET ; do
		SECTOR=$((SECTOR+1))
		echo $BET | sed -e 's/ *$//' -e 's/ /\n/g' | while read BET_VALUE ; do
			LINE=$(echo "(${BET_VALUE}-1)%5" | bc)
			COLUMN=$(echo "4-((${BET_VALUE}-1)/5)" | bc)
			echo $SECTOR $LINE $COLUMN
		done
	done
}

metapost_bullet() {

	COLOR=$1
	SECTOR=$2
	LINE=$3
	COLUMN=$4

	BULLET_WIDTH='3.5'
	BULLET_HEIGHT='5'

	X_ZERO='25.5'; X_DELTA='5.5'; SECTOR_X_DELTA='31'
	Y_ZERO='10'; Y_DELTA='12.9'

	local X=$(echo "${X_ZERO} + ${SECTOR}*${SECTOR_X_DELTA} + ${LINE}*${X_DELTA}" | bc)
	local Y=$(echo "${Y_ZERO} + ${COLUMN}*${Y_DELTA}" | bc)
	echo "draw (${X}mm,${Y}mm) withcolor $COLOR withpen pencircle xscaled ${BULLET_WIDTH}mm yscaled ${BULLET_HEIGHT}mm;"

}

data_to_metapost() {

	local LABEL="$1"

	echo 'prologues := 3;'
	echo 'beginfig(-1);'
	echo "draw (0,0) withpen pencircle scaled 0 withcolor white;"

	echo -e "1\n25" | bets_to_data | while read SECTOR LINE COLUMN ; do
		metapost_bullet 'white' $SECTOR $LINE $COLUMN
	done

	while read SECTOR LINE COLUMN ; do
		metapost_bullet 'black' $SECTOR $LINE $COLUMN
	done

	echo "label.lft(\"${LABEL}\",(130mm,10mm))"

	echo 'endfig;'
	echo 'end;'
}

ERR_FILE=$(mktemp)
find $RESULT_DIR -mindepth 1 -maxdepth 1 -type f -name 'bets.*' | while read BET_FILE_OLD ; do
	ID=$(echo "$BET_FILE_OLD" | sed -e 's/.*\.//')
	BET_FILE="$RESULT_DIR/${ID}.bets"
	mv $BET_FILE_OLD $BET_FILE
	DATA_FILE="$RESULT_DIR/${ID}.data"
	bets_to_data 0<$BET_FILE 1>$DATA_FILE
	METAPOST_FILE="$RESULT_DIR/${ID}.mp"
	LABEL="${GROUP_LABEL}-${ID}"
	data_to_metapost "$LABEL" 0<$DATA_FILE 1>$METAPOST_FILE
	( cd $RESULT_DIR && mpost $ID 1>$ERR_FILE 2>&1 ) || {
		cat $ERR_FILE 1>&2
		exit 1
	}
	PS_FILE="$RESULT_DIR/${ID}.ps"
	BBOX_WIDTH=$(identify $PS_FILE | awk '{print $3}' | awk -Fx '{print $1}')
	BBOX_HEIGHT=$(identify $PS_FILE | awk '{print $3}' | awk -Fx '{print $2}')
	( cd $RESULT_DIR && ps2pdf -dDEVICEWIDTHPOINTS=${BBOX_WIDTH} -dDEVICEHEIGHTPOINTS=$((BBOX_HEIGHT+41)) "${ID}.ps" )
done
rm -f $ERR_FILE

PDF_FILES=$(find $RESULT_DIR -mindepth 1 -maxdepth 1 -type f -name '*.pdf' -exec basename '{}' ';' | sort -n | tr '\n' ' ')
( cd $RESULT_DIR && gs -q -sPAPERSIZE=a4 -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile='all_bets.pdf' $PDF_FILES )

echo "files generated in directory '${RESULT_DIR}'." 1>&2

