#!/bin/bash

set -e

usage() {
	echo "usage: ./bets_lotofacil TUPLE_SIZE GROUP_LABEL" 1>&2
	exit 1
}

TUPLE_SIZE=$1
test -n "$TUPLE_SIZE" || usage
shift
GROUP_LABEL=$1
test -n "$GROUP_LABEL" || usage
shift
test -z "$1" || usage

RESULT_DIR="lotofacil/${GROUP_LABEL}"
mkdir -p $RESULT_DIR

ALL_BETS_FILE_NAME="${TUPLE_SIZE}-15-25.all"
ALL_BETS_FILE="${RESULT_DIR}/${ALL_BETS_FILE_NAME}"
./bets "$TUPLE_SIZE" 15 25 1>$ALL_BETS_FILE
(
	cd $RESULT_DIR
	split -d -l 2 -a 4 $ALL_BETS_FILE_NAME 'bets.'
)

##FIXME: debug
#echo -n 1>$RESULT_DIR/bets.0000
#for I in 0 1 ; do
	#seq -s ' ' 1 25 1>>$RESULT_DIR/bets.0000
#done

bets_to_data() {
	local SECTOR='-1'
	local LINE
	local COLUMN
	while read BET ; do
		SECTOR=$((SECTOR+1))
		echo $BET | sed -e 's/ *$//' -e 's/ /\n/g' | while read BET_VALUE ; do
			LINE=$(echo "(${BET_VALUE}-1)%5" | bc)
			COLUMN=$(echo "4-((${BET_VALUE}-1)/5)" | bc)
			echo $SECTOR $LINE $COLUMN
		done
	done
}

data_to_metapost() {

	X_ALL=82; X_ZERO=14; X_DELTA='12.75'
	Y_ALL=140; Y_ZERO='60.5'; Y_DELTA='5.6'; SECTOR_DELTA=31

	echo 'beginfig(-1);'
	echo "draw (0,0)--(${X_ALL}mm,${Y_ALL}mm) withpen pencircle scaled 0 withcolor white;"
	while read SECTOR LINE COLUMN ; do

		SECTOR=$((1-SECTOR))
		LINE=$((4-LINE))

		X=$(echo "${X_ZERO} + ${COLUMN}*${X_DELTA}" | bc)
		Y=$(echo "${Y_ZERO} + ${SECTOR}*${SECTOR_DELTA} + ${LINE}*${Y_DELTA}" | bc)

		echo "draw (${X}mm,${Y}mm) withpen pencircle xscaled 15bp yscaled 10bp;"

	done
	echo 'endfig;'
	echo 'end;'
}

find $RESULT_DIR -mindepth 1 -maxdepth 1 -type f -name 'bets.*' | while read BET_FILE_OLD ; do
	ID=$(echo "$BET_FILE_OLD" | sed -e 's/.*\.//')
	BET_FILE="$RESULT_DIR/${ID}.bets"
	mv $BET_FILE_OLD $BET_FILE
	DATA_FILE="$RESULT_DIR/${ID}.data"
	bets_to_data 0<$BET_FILE 1>$DATA_FILE
	METAPOST_FILE="$RESULT_DIR/${ID}.mp"
	data_to_metapost 0<$DATA_FILE 1>$METAPOST_FILE
	( cd $RESULT_DIR && mpost $ID )
done

echo "files generated in directory '${RESULT_DIR}'." 1>&2

