#!/bin/sh

set -e

RESULTS_URL='http://www1.caixa.gov.br/loterias/_arquivos/loterias/d_dplsen.zip'
RESULTS_ZIP_FILE=$(mktemp)

wget -q -O $RESULTS_ZIP_FILE "$RESULTS_URL"

unzip -p $RESULTS_ZIP_FILE D_DPLSEN.HTM | \
tidy -qi 2>/dev/null | \
xmllint --format --html --xmlout - | \
xmlstarlet sel -T -t -m '/html/body/table[1]/tr[position()!=1]' -v 'td[1]' -o ' - ' \
	-v 'td[3]' -o ' ' \
	-v 'td[4]' -o ' ' \
	-v 'td[5]' -o ' ' \
	-v 'td[6]' -o ' ' \
	-v 'td[7]' -o ' ' \
	-v 'td[8]' -o ' ' \
	-n

rm -f $RESULTS_ZIP_FILE

